package com.conreo.couchytv.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import android.os.SystemClock
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.input.key.Key
import androidx.compose.ui.input.key.KeyEventType
import androidx.compose.ui.input.key.key
import androidx.compose.ui.input.key.onPreviewKeyEvent
import androidx.compose.ui.input.key.type
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.tv.material3.Border
import androidx.tv.material3.ClickableSurfaceDefaults
import androidx.tv.material3.Glow
import androidx.tv.material3.MaterialTheme
import androidx.tv.material3.Surface
import androidx.tv.material3.Text
import androidx.compose.foundation.BorderStroke
import com.conreo.couchytv.data.AppEntry


@Composable
fun AppCard(
    app: AppEntry,
    isMoving: Boolean,
    isHidden: Boolean,
    accent: Color,
    cardWidth: androidx.compose.ui.unit.Dp = 190.dp,
    showLabel: Boolean = true,
    modifier: Modifier = Modifier,
    onLaunch: () -> Unit,
    onLongPress: () -> Unit,
) {
    // Long-press handling. The launcher must never do BOTH actions, and the
    // trap is that releasing OK after a hold still arrives as a normal click
    // on the Surface (its own built-in handler) — which launched the app
    // behind the freshly opened menu. So instead of fighting the key events,
    // we detect the hold ourselves and then SUPPRESS the click that follows
    // it, using a short time window that expires on its own (a sticky flag
    // would eat the next legitimate press, since the release is delivered to
    // the menu's window and never comes back to this card).
    val cardShape = SmoothCornerShape(LocalCornerRadius.current)
    var downAt by remember { mutableLongStateOf(0L) }
    var lastKeyDown by remember { mutableLongStateOf(0L) }
    var longPressAt by remember { mutableLongStateOf(0L) }

    fun fireLongPress() {
        longPressAt = SystemClock.uptimeMillis()
        onLongPress()
    }

    // Focus: the card grows a touch, lifts on a soft tight shadow, and gains a
    // thin accent ring — crisp to read across a room.
    Surface(
        onClick = {
            // Ignore the click generated by releasing a long press.
            if (SystemClock.uptimeMillis() - longPressAt > 1_000L) onLaunch()
        },
        onLongClick = { fireLongPress() }, // pointer / mouse path
        modifier = modifier
            .onPreviewKeyEvent { e ->
                val select = e.key == Key.DirectionCenter || e.key == Key.Enter ||
                    e.key == Key.NumPadEnter
                if (!select || e.type != KeyEventType.KeyDown) return@onPreviewKeyEvent false
                val now = SystemClock.uptimeMillis()
                // Auto-repeats arrive every 50-100ms; a gap >300ms means a new press.
                if (lastKeyDown == 0L || now - lastKeyDown > 300) {
                    downAt = now
                    lastKeyDown = now
                    return@onPreviewKeyEvent false // let the normal click path work
                }
                lastKeyDown = now
                if (now - longPressAt > 1_000L && now - downAt >= 450) {
                    fireLongPress()
                }
                true // swallow the repeats themselves
            }
            .width(cardWidth),
        shape = ClickableSurfaceDefaults.shape(cardShape),
        colors = ClickableSurfaceDefaults.colors(
            containerColor = app.tile,
            focusedContainerColor = app.tile,
            contentColor = Color.White,
            focusedContentColor = Color.White,
        ),
        scale = ClickableSurfaceDefaults.scale(focusedScale = 1.10f),
        glow = ClickableSurfaceDefaults.glow(
            // Softer + tighter than before: reads at 3m, cheap to render on weak
            // TV GPUs, and no longer competes with the accent ring.
            focusedGlow = Glow(elevationColor = Color.Black.copy(alpha = 0.5f), elevation = 8.dp)
        ),
        border = ClickableSurfaceDefaults.border(
            // Thin accent ring on focus (thicker while dragging in move mode).
            focusedBorder = Border(
                BorderStroke(if (isMoving) 3.dp else 2.dp, accent),
                shape = cardShape,
            )
        ),
    ) {
        Box(
            Modifier
                .fillMaxWidth()
                .aspectRatio(16f / 9f)
        ) {
            if (app.banner != null) {
                Image(
                    bitmap = app.banner,
                    contentDescription = app.label,
                    contentScale = ContentScale.Crop,
                    // Own render layer: the focus scale animation transforms the
                    // cached layer instead of re-drawing (re-sampling) the bitmap.
                    modifier = Modifier.fillMaxSize().graphicsLayer { },
                )
            } else {
                // Banner-less apps: give the flat tile depth with a subtle sheen
                // (light top, dark bottom) so it sits next to real banners.
                Box(
                    Modifier
                        .fillMaxSize()
                        .background(
                            androidx.compose.ui.graphics.Brush.verticalGradient(
                                listOf(
                                    Color.White.copy(alpha = 0.10f),
                                    Color.Transparent,
                                    Color.Black.copy(alpha = 0.14f),
                                )
                            )
                        )
                )
                Column(
                    Modifier
                        .fillMaxSize()
                        .padding(8.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    Box(Modifier.weight(1f), contentAlignment = Alignment.Center) {
                        if (app.icon != null) {
                            Image(
                                bitmap = app.icon,
                                contentDescription = null,
                                modifier = Modifier.size(48.dp),
                            )
                        }
                    }
                    if (showLabel) {
                        Text(
                            text = app.label,
                            style = MaterialTheme.typography.labelMedium,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis,
                        )
                    }
                }
            }
            if (isHidden) {
                Box(
                    Modifier
                        .fillMaxSize()
                        .background(Color.Black.copy(alpha = 0.6f))
                )
            }
        }
    }
}
