package com.gothwad.launcher.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import android.os.SystemClock
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsFocusedAsState
import androidx.compose.foundation.interaction.collectIsHoveredAsState
import androidx.compose.foundation.hoverable
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.input.key.Key
import androidx.compose.ui.input.key.KeyEventType
import androidx.compose.ui.input.key.key
import androidx.compose.ui.input.key.onPreviewKeyEvent
import androidx.compose.ui.input.key.type
import androidx.compose.ui.input.pointer.PointerEventPass
import androidx.compose.ui.input.pointer.PointerEventType
import androidx.compose.ui.input.pointer.PointerIcon
import androidx.compose.ui.input.pointer.isSecondaryPressed
import androidx.compose.ui.input.pointer.pointerHoverIcon
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.tv.material3.Border
import androidx.tv.material3.ClickableSurfaceDefaults
import androidx.tv.material3.Glow
import androidx.tv.material3.MaterialTheme
import androidx.tv.material3.Surface
import androidx.tv.material3.Text
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.shape.CircleShape
import androidx.tv.material3.Icon
import com.gothwad.launcher.data.AppEntry

@Composable
fun AppCard(
    app: AppEntry,
    isMoving: Boolean,
    isHidden: Boolean = false,
    isLocked: Boolean = false,
    accent: Color,
    cardWidth: androidx.compose.ui.unit.Dp = 190.dp,
    showLabel: Boolean = true,
    modifier: Modifier = Modifier,
    onLaunch: () -> Unit,
    onLongPress: () -> Unit,
) {
    // Long-press handling. The launcher must never do BOTH actions, and the
    // trap is that releasing OK after a hold still arrives as a normal click
    // on the Surface (its own built-in handler) — which launched the app
    // behind the freshly opened menu. So instead of fighting the key events,
    // we detect the hold ourselves and then SUPPRESS the click that follows
    // it, using a short time window that expires on its own (a sticky flag
    // would eat the next legitimate press, since the release is delivered to
    // the menu's window and never comes back to this card).
    val currentCornerRadius = LocalCornerRadius.current
    val cardShape = remember(currentCornerRadius) { SmoothCornerShape(currentCornerRadius) }
    val interactionSource = remember { MutableInteractionSource() }
    val isHovered by interactionSource.collectIsHoveredAsState()
    val isFocused by interactionSource.collectIsFocusedAsState()
    val hoverScale by animateFloatAsState(
        targetValue = if (isHovered && !isFocused) 1.06f else 1.0f,
        label = "hoverScale",
    )
    var downAt by remember { mutableLongStateOf(0L) }
    var lastKeyDown by remember { mutableLongStateOf(0L) }
    var longPressAt by remember { mutableLongStateOf(0L) }

    fun fireLongPress() {
        longPressAt = SystemClock.uptimeMillis()
        onLongPress()
    }

    // Focus / Hover: grows, lifts, and shows accent ring. Works with TV Remote D-Pad, Mouse hover/clicks, Touch, and Keyboard.
    Surface(
        onClick = {
            // Ignore the click generated by releasing a long press.
            if (SystemClock.uptimeMillis() - longPressAt > 1_000L) onLaunch()
        },
        onLongClick = { fireLongPress() }, // pointer / mouse long-press path
        interactionSource = interactionSource,
        modifier = modifier
            .width(cardWidth)
            .pointerHoverIcon(PointerIcon.Hand)
            .hoverable(interactionSource)
            .then(
                if (hoverScale != 1.0f) {
                    Modifier.graphicsLayer {
                        scaleX = hoverScale
                        scaleY = hoverScale
                    }
                } else Modifier
            )
            .pointerInput(Unit) {
                awaitPointerEventScope {
                    while (true) {
                        val event = awaitPointerEvent(PointerEventPass.Main)
                        if (event.type == PointerEventType.Press &&
                            event.buttons.isSecondaryPressed
                        ) {
                            fireLongPress()
                        }
                    }
                }
            }
            .onPreviewKeyEvent { e ->
                if (e.type == KeyEventType.KeyDown && e.key == Key.Menu) {
                    fireLongPress()
                    return@onPreviewKeyEvent true
                }
                val select = e.key == Key.DirectionCenter || e.key == Key.Enter ||
                    e.key == Key.NumPadEnter || e.key == Key.Spacebar
                if (!select || e.type != KeyEventType.KeyDown) return@onPreviewKeyEvent false
                val now = SystemClock.uptimeMillis()
                // Auto-repeats arrive every 50-100ms; a gap >300ms means a new press.
                if (lastKeyDown == 0L || now - lastKeyDown > 300) {
                    downAt = now
                    lastKeyDown = now
                    return@onPreviewKeyEvent false // let the normal click path work
                }
                lastKeyDown = now
                if (now - longPressAt > 1_000L && now - downAt >= 450) {
                    fireLongPress()
                }
                true // swallow the repeats themselves
            },
        shape = ClickableSurfaceDefaults.shape(cardShape),
        colors = ClickableSurfaceDefaults.colors(
            containerColor = app.tile,
            focusedContainerColor = app.tile,
            contentColor = Color.White,
            focusedContentColor = Color.White,
        ),
        scale = ClickableSurfaceDefaults.scale(focusedScale = 1.10f),
        glow = ClickableSurfaceDefaults.glow(
            focusedGlow = Glow.None
        ),
        border = ClickableSurfaceDefaults.border(
            border = if (isHovered && !isFocused) Border(BorderStroke(2.dp, accent.copy(alpha = 0.8f)), shape = cardShape)
                     else Border.None,
            focusedBorder = Border(
                BorderStroke(if (isMoving) 3.dp else 2.dp, accent),
                shape = cardShape,
            )
        ),
    ) {
        Box(
            Modifier
                .fillMaxWidth()
                .aspectRatio(16f / 9f)
        ) {
            if (app.banner != null) {
                Image(
                    bitmap = app.banner,
                    contentDescription = app.label,
                    contentScale = ContentScale.Crop,
                    modifier = Modifier.fillMaxSize(),
                )
            } else {
                // Banner-less apps: give the flat tile depth with a subtle sheen
                // (light top, dark bottom) so it sits next to real banners.
                Box(
                    Modifier
                        .fillMaxSize()
                        .background(
                            androidx.compose.ui.graphics.Brush.verticalGradient(
                                listOf(
                                    Color.White.copy(alpha = 0.10f),
                                    Color.Transparent,
                                    Color.Black.copy(alpha = 0.14f),
                                )
                            )
                        )
                )
                Column(
                    Modifier
                        .fillMaxSize()
                        .padding(8.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                ) {
                    Box(Modifier.weight(1f), contentAlignment = Alignment.Center) {
                        if (app.icon != null) {
                            Image(
                                bitmap = app.icon,
                                contentDescription = null,
                                modifier = Modifier.size(48.dp),
                            )
                        }
                    }
                    if (showLabel) {
                        Text(
                            text = app.label,
                            style = MaterialTheme.typography.labelMedium,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis,
                        )
                    }
                }
            }
            if (isLocked) {
                Box(
                    Modifier
                        .align(Alignment.TopEnd)
                        .padding(6.dp)
                        .size(22.dp)
                        .background(Color.Black.copy(alpha = 0.65f), CircleShape),
                    contentAlignment = Alignment.Center,
                ) {
                    Icon(
                        imageVector = AppIcons.Lock,
                        contentDescription = "Locked",
                        tint = Color(0xFFFFD54F),
                        modifier = Modifier.size(13.dp),
                    )
                }
            }
        }
    }
}
